INSERT INTO VAINQUEURS(Annee,Champion,Grimpeur,Sprinter)
VALUES
	(1975,	'Bernard Thevenet','Lucien van Impe','Rik Van Linden'),	
	(1976,	'Lucien Van Impe','Giancarlo Bellini','Freddy Maertens'),	
	(1977,	'Bernard Thevenet','Lucien van Impe','Jacques Esclassan'),	
	(1978,	'Bernard Hinault','Mariano Martinez','Freddy Maertens'),
	(1979,	'Bernard Hinault','Giovanni Battaglin','Bernard Hinault'),
	(1980,	'Joop Zoetemelk','Raymond Martin','Rudy Pevenage'),
	(1981,	'Bernard Hinault','Lucien van Impe','Freddy Maertens'),	
	(1982,	'Bernard Hinault','Bernard Vallet','Sean Kelly'),	
	(1983,	'Laurent Fignon','Lucien van Impe','Sean Kelly'),
	(1984,	'Laurent Fignon','Robert Millar','Frank Hoste'),
	(1985,	'Bernard Hinault','Luis Herrera','Sean Kelly'),	
	(1986,	'Greg Lemond','Bernard Hinault','Eric Vanderaerden'),
	(1987,	'Stephen Roche','Luis Herrera','Jean-Paul van Poppel'),	
	(1988,	'Pedro Delgado','Steven Rooks','Eddy Planckaert'),
	(1989,	'Greg Lemond','Gert-Jan Theunisse','Sean Kelly'),
	(1990,	'Greg Lemond','Thierry Claveyrolat','Olaf Ludwig'),
	(1991,	'Miguel Indurain','Claudio Chiappucci','Djamol Abdoujaparov'),	
	(1992,	'Miguel Indurain','Claudio Chiappucci','Laurent Jalabert'),	
	(1993,	'Miguel Indurain','Tony Rominger','Djamol Abdoujaparov'),	
	(1994,	'Miguel Indurain','Richard Virenque','Djamol Abdoujaparov'),	
	(1995,	'Miguel Indurain','Richard Virenque','Laurent Jalabert'),	
	(1996,	'Bjarne Riis','Richard Virenque','Erik Zabel'),
	(1997,	'Jan Ullrich','Richard Virenque','Erik Zabel'),
	(1998,	'Marco Pantani','Christophe Rinero','Erik Zabel'),
	(1999,	'Sans vainqueur','Richard Virenque','Erik Zabel'),
	(2000,	'Sans vainqueur','Santiago Botero','Erik Zabel'),
	(2001,	'Sans vainqueur','Laurent Jalabert','Erik Zabel'),
	(2002,	'Sans vainqueur','Laurent Jalabert','Robbie McEwen'),
	(2003,	'Sans vainqueur','Richard Virenque','Baden Cooke'),
	(2004,	'Sans vainqueur','Richard Virenque','Robbie McEwen'),
	(2005,	'Sans vainqueur','Michael Rasmussen','Thor Hushovd'),
	(2006,	'Óscar Pereiro','Michael Rasmussen','Robbie McEwen'),
	(2007,	'Alberto Contador','Juan Mauricio Soler Hernandez','Tom Boonen'),	
	(2008,	'Carlos Sastre','Bernhard Kohl','Óscar Freire'),	
	(2009,	'Alberto Contador','Franco Pellizotti','Thor Hushovd'),	
	(2010,	'Andy Schleck','Anthony Charteau','Alessandro Petacchi'),	
	(2011,	'Cadel Evans','Samuel Sanchez','Mark Cavendish'),	
	(2012,	'Bradley Wiggins','Thomas Voeckler','Peter Sagan'),	
	(2013,	'Christopher Froome','Nairo Quintana','Peter Sagan'),	
	(2014,	'Vincenzo Nibali','Rafal Majka','Peter Sagan'),	
	(2015,	'Christopher Froome','Christopher Froome','Peter Sagan'),
	(2016,	'Christopher Froome','Rafal Majka','Peter Sagan'),
	(2017, 'Christopher Froome', 'Warren Barguil','Michael Matthews')



